name: dating_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1 
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_spinkit: ^5.2.1
  permission_handler: ^11.3.1
  intl: ^0.18.0
  numberpicker: ^2.1.2
  shared_preferences: ^2.3.2
  pinput: ^5.0.0
  fluttertoast: ^8.2.8
  http: ^1.2.2
  mime: ^2.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
