name: dating_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.3
  image_picker: ^1.1.2
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_spinkit: ^5.2.1
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  numberpicker: ^2.1.2
  shared_preferences: ^2.3.3
  pinput: ^5.0.0
  fluttertoast: ^8.2.8
  http: ^1.3.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_slider_indicator: ^1.0.0
  video_player: ^2.9.5
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  encrypt_shared_preferences: ^0.9.9
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_auth: ^5.3.3
  flutter_local_notifications: ^19.2.0
  flutter_image_compress: ^2.3.0
  flutter_keyboard_visibility: ^6.0.0
  curved_navigation_bar: ^1.0.6
  swipe_cards: ^2.0.0+1
  cached_network_image: ^3.4.1
  lightning_overlay: ^0.0.8
  liquid_swipe: ^3.1.0
  pusher_channels_flutter: ^2.4.0
  web_socket_channel: ^3.0.1
  stomp_dart_client: ^2.1.0
  razorpay_flutter: ^1.3.7
  carousel_slider: ^5.0.0
  lottie: ^3.3.0
  skeletonizer: ^1.4.2
  vibration: ^3.1.3
  flutter_slidable: ^4.0.0
  uuid: ^4.5.1
  chat_bubbles: ^1.6.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  flutter_animated_button: ^2.0.4
  pushable_button: ^0.0.4
  heart_overlay: ^1.4.1
  intl_phone_number_input: ^0.7.4
  pull_to_refresh_flutter3: ^2.0.2
  agora_rtc_engine: ^6.5.2
  audioplayers: ^6.1.1
  icons_plus: ^5.0.0
  aurora_background: ^1.0.1
  super_tooltip: ^2.0.9
  font_awesome_flutter: ^10.8.0
  flutter_speed_dial: ^7.0.0
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  http_parser: ^4.1.2
  country_code_picker: ^3.3.0
  sqflite: ^2.4.2
  slide_to_act: ^2.0.2
  path: ^1.9.1
  logging: ^1.0.2
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cajed_logo.png"
  remove_alpha_ios : true

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/call.mp3
    - assets/images/like.png
    - assets/images/heart.png
    - assets/images/dislike.png
    - assets/images/coin.png
    - assets/images/techlead.jpg
    - assets/images/emoji/
    - assets/images/
    - assets/animations/

  fonts:
    - family: RusticRoadway
      fonts:
        - asset: assets/fonts/RusticRoadway-Italic.ttf
