name: dating_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1 
  flutter_secure_storage: ^9.2.3
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_spinkit: ^5.2.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  numberpicker: ^2.1.2
  shared_preferences: ^2.3.3
  pinput: ^5.0.0
  fluttertoast: ^8.2.8
  http: ^1.3.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_slider_indicator: ^1.0.0
  video_player: ^2.9.2
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  encrypt_shared_preferences: ^0.8.3
  firebase_core: ^3.8.0 
  firebase_messaging: ^15.1.5
  firebase_auth: ^5.3.3
  flutter_local_notifications: ^18.0.1
  flutter_image_compress: ^2.3.0
  flutter_keyboard_visibility: ^6.0.0
  curved_navigation_bar: ^1.0.6
  swipe_cards: ^2.0.0+1
  cached_network_image: ^3.2.0
  lightning_overlay: ^0.0.8
  liquid_swipe: ^3.1.0
  pusher_channels_flutter: ^2.4.0
  web_socket_channel: ^3.0.1
  stomp_dart_client: ^2.1.0
  razorpay_flutter: ^1.3.7
  carousel_slider: ^5.0.0
  lottie: ^3.3.0
  skeletonizer: ^1.4.2
  vibration: ^2.0.1
  flutter_slidable: ^3.1.2
  uuid: ^4.5.1
  chat_bubbles: ^1.6.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  flutter_animated_button: ^2.0.4
  pushable_button: ^0.0.4
  heart_overlay: ^1.4.1
  intl_phone_number_input: ^0.7.4





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/blockanimation.json
    - assets/animations/Buyanimation.json
    - assets/animations/dislikeswipeanimation.json
    - assets/animations/likeswipeanimation.json
    - assets/animations/notificationanimation.json
    - assets/animations/paymentdoneanimation.json
    - assets/animations/superlikeswipeanimation.json
    - assets/animations/thumblikeanimation.json
    - assets/animations/waitinganimation.json
    - assets/animations/likepageanimation.json
    - assets/animations/couplematchanimation.json
    - assets/animations/chatpageanimation.json
    - assets/animations/shareappanimation.json
    - assets/animations/homepageanimation.json
    - assets/animations/requestmessageanimation.json
    - assets/animations/savedanimation.json
    - assets/animations/homeanimation.json
    - assets/animations/404animation.json
    - assets/animations/editprofileanimation.json
    - assets/animations/handloadinganimation.json
    - assets/animations/new404animation.json
    - assets/animations/likesbuttonpressanimation.json
    
    
